-- Role Seeding Script for Student Performance Tracker
-- This script creates the three essential roles in the system

-- Insert roles into the roles table
-- Note: The ID values will be auto-generated by the database
INSERT INTO roles (name, normalized_name, concurrency_stamp)
VALUES 
    ('Admin', 'ADMIN', NEWID()),
    ('Teacher', 'TEACHER', NEWID()),
    ('Student', 'STUDENT', NEWID());

-- Verify the roles were inserted
SELECT 
    id,
    name,
    normalized_name,
    concurrency_stamp
FROM roles
ORDER BY name;

-- Expected output:
-- id | name    | normalized_name | concurrency_stamp
-- ---|---------|-----------------|------------------
-- 1  | Admin   | ADMIN          | [GUID]
-- 2  | Student | STUDENT        | [GUID]  
-- 3  | Teacher | TEACHER        | [GUID]
